SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `tripdb`.`associata`;
DROP TABLE IF EXISTS `tripdb`.`camera`;
DROP TABLE IF EXISTS `tripdb`.`cliente`;
DROP TABLE IF EXISTS `tripdb`.`comfort`;
DROP TABLE IF EXISTS `tripdb`.`dipendente`;
DROP TABLE IF EXISTS `tripdb`.`documentazionefotografica`;
DROP TABLE IF EXISTS `tripdb`.`fme`;
DROP TABLE IF EXISTS `tripdb`.`fmo`;
DROP TABLE IF EXISTS `tripdb`.`localita`;
DROP TABLE IF EXISTS `tripdb`.`mappa`;
DROP TABLE IF EXISTS `tripdb`.`meta`;
DROP TABLE IF EXISTS `tripdb`.`mezzo`;
DROP TABLE IF EXISTS `tripdb`.`modello`;
DROP TABLE IF EXISTS `tripdb`.`offre`;
DROP TABLE IF EXISTS `tripdb`.`postoprenotato`;
DROP TABLE IF EXISTS `tripdb`.`prenotazione`;
DROP TABLE IF EXISTS `tripdb`.`presenti`;
DROP TABLE IF EXISTS `tripdb`.`rt`;
DROP TABLE IF EXISTS `tripdb`.`revisione`;
DROP TABLE IF EXISTS `tripdb`.`ricambio`;
DROP TABLE IF EXISTS `tripdb`.`servizio`;
DROP TABLE IF EXISTS `tripdb`.`tagliando`;
DROP TABLE IF EXISTS `tripdb`.`tome`;
DROP TABLE IF EXISTS `tripdb`.`tour`;
DROP TABLE IF EXISTS `tripdb`.`utente`;
DROP TABLE IF EXISTS `tripdb`.`viaggio`;
DROP TABLE IF EXISTS `tripdb`.`visita`;

SET FOREIGN_KEY_CHECKS = 1;